import esbuild from "esbuild";
import builtinModules from "builtin-modules";
import process from "node:process";
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";

const require = createRequire(import.meta.url);
const production = process.argv.includes("production");
const watch = process.argv.includes("--watch");

const external = [
  "obsidian",
  "electron",
  "node-pty",
  "@codemirror/*",
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`)
];

const buildOptions = {
  banner: {
    js: "/* MiniTerm Obsidian plugin - generated by esbuild. */"
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external,
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  platform: "browser",
  sourcemap: production ? false : "inline",
  target: "es2022",
  treeShaking: true
};

async function writeStyles() {
  const xtermCssPath = require.resolve("@xterm/xterm/css/xterm.css");
  const [xtermCss, localCss] = await Promise.all([
    readFile(xtermCssPath, "utf8"),
    readFile("src/styles.css", "utf8")
  ]);

  await writeFile(
    "styles.css",
    [
      "/* @xterm/xterm base styles, copied at build time. */",
      xtermCss.trim(),
      "",
      "/* MiniTerm styles. */",
      localCss.trim(),
      ""
    ].join("\n")
  );
}

if (watch) {
  const context = await esbuild.context(buildOptions);
  await context.watch();
  await writeStyles();
  console.log("MiniTerm build is watching src/main.ts. Re-run build after CSS-only edits.");
} else {
  await esbuild.build(buildOptions);
  await writeStyles();
}
