ClearAll["Global`*"];
checks={}; add[n_,r_]:=AppendTo[checks,n->FullSimplify[r]];
X={{x1,x2},{x2,x3}}; HH={{h1,h2},{h2,h3}}; zz={z1,z2}; dz={{d11,d12},{d21,d22}}; ep={{0,1},{-1,0}};
rh=-kg-(Tr[X] Tr[HH]-Tr[X.HH])/2;
sg=d12-d21+(X.HH-HH.X)[[1,2]]/2;
rawMinus=2 dz+2 Outer[Times,zz,zz]+rh IdentityMatrix[2]-sg ep-HH.X-2 nv X;
closedMinus=dz+Transpose[dz]+2 Outer[Times,zz,zz]-kg IdentityMatrix[2]-(2nv+Tr[HH]/2)X-Tr[X]/2 HH;
add["V54 mixed minus full-to-symmetric",rawMinus-closedMinus];
add["V54 two-dimensional Gauss matrix identity",(HH.X+X.HH)/2+(Tr[X]Tr[HH]-Tr[X.HH])/2 IdentityMatrix[2]-(Tr[HH] X+Tr[X] HH)/2];
dt=-dz; tt={t1,t2};
rawPlus=2 dt+2 Outer[Times,tt,tt]+rh IdentityMatrix[2]+sg ep-X.HH;
closedPlus=dt+Transpose[dt]+2 Outer[Times,tt,tt]-kg IdentityMatrix[2]-Tr[X]/2 HH-Tr[HH]/2 X;
add["V55 mixed plus normal-curvature cancellation",rawPlus-closedPlus];
(* Slots: alpha(2), underalpha(2), beta(2), underbeta(2), rho,sigma,cbet(2),cubet(2),crho,csigma. *)
perm={1,2,3,4,11,12,13,14,15,16,5,6,7,8,9,10};
PP=IdentityMatrix[16][[perm]];
add["V56 copy permutation involution",PP.PP-IdentityMatrix[16]];
phiR={1,2,5,6,7,8,15,16}; phiP={1,2,9,10,11,12,13,14};
ar=DiagonalMatrix[Table[Boole[MemberQ[phiR,j]],{j,16}]];
ap=DiagonalMatrix[Table[Boole[MemberQ[phiP,j]],{j,16}]];
add["V56 null principal allocation",PP.ar.Transpose[PP]-ap];
copy=Table[UnitVector[16,j+6]-UnitVector[16,j],{j,5,10}];
add["V56 copy ideal changes sign",copy.PP+copy];
(* All four literal Appendix angular blocks, independently listed by slot. *)
ks[pairs_]:=Total[(With[{i=#[[1]],j=#[[2]],s=#[[3]]},s(Outer[Times,UnitVector[16,i],UnitVector[16,j]]+Outer[Times,UnitVector[16,j],UnitVector[16,i]])])&/@pairs];
kr1=ks[{{3,7,1},{4,8,1},{15,13,1},{16,14,1},{9,5,-1},{10,6,1},{1,11,-1},{2,12,-1}}];
kr2=ks[{{3,8,-1},{4,7,1},{15,14,1},{16,13,-1},{9,6,-1},{10,5,-1},{1,12,1},{2,11,-1}}];
kp1=ks[{{3,13,1},{4,14,1},{9,7,1},{10,8,1},{15,11,-1},{16,12,1},{1,5,-1},{2,6,-1}}];
kp2=ks[{{3,14,-1},{4,13,1},{9,8,1},{10,7,-1},{15,12,-1},{16,11,-1},{1,6,1},{2,5,-1}}];
add["V56 all four angular blocks conjugate",{PP.kr1.PP-kp1,PP.kr2.PP-kp2}];
add["V56 fixed off-diagonal angular structure",{ap.kp1.ap,ap.kp2.ap,(IdentityMatrix[16]-ap).kp1.(IdentityMatrix[16]-ap),(IdentityMatrix[16]-ap).kp2.(IdentityMatrix[16]-ap)}];
add["V57 unchanged RHS counterexample value",(-3 x1 cr+3 x1 rr/.{x1->1,cr->1,rr->0})+3];
uu={u1[t],u2[t]}; aa={{a[t],b[t]},{b[t],d[t]}}; ht={{hh1[t],0},{0,hh2[t]}}; sym=ht.aa+Transpose[ht.aa];
cur=j[t] uu.sym.uu;
add["V58 symmetrizer-density product rule",D[cur,t]-2j[t]uu.sym.D[uu,t]-uu.D[j[t]sym,t].uu];
gg[p_,q_]:=p q+p^2; kk[p_,q_]:=1+p+q^2;
hh[p_,q_]:=p^2+q^2; ll[p_,q_]:=2+p q; vel[p_,q_]:=p+q;
uv=gg[p,q]-kk[p,q] qx; vv=hh[p,q]-vel[p,q] qx-ll[p,q] px;
dx[expr_]:=D[expr,p]px+D[expr,q]qx+D[expr,px]pxx+D[expr,qx]qxx;
bz=D[gg[p,q],p]-D[kk[p,q],p]qx;
fz=D[gg[p,q],q]vv-D[kk[p,q],q]vv qx-kk[p,q]dx[vv];
by=D[hh[p,q],q]-D[ll[p,q],q]px-D[vel[p,q],q]qx;
fy=D[hh[p,q],p]uv-D[ll[p,q],p]uv px-ll[p,q]dx[uv]-D[vel[p,q],p]uv qx;
add["V59 differentiated phi elimination",D[uv,p]zt+D[uv,q]vv+D[uv,qx]dx[vv]-(bz zt+fz)];
add["V59 differentiated psi elimination",D[vv,p]uv+D[vv,q]yt+D[vv,px]dx[uv]+D[vv,qx]dyx+vel[p,q]dyx-(by yt+fy)];
Scan[Print[If[And@@Thread[Flatten[{Last[#]}]==0],"PASS ","FAIL "],First[#]]&,checks];
If[!And@@(And@@Thread[Flatten[{Last[#]}]==0]&/@checks),Print["FAILED"];Exit[1]];
Print["UNCHANGED_RHS diagnostic has value -3; it is not a zero residual."];
Print["REGRESSIONS ONLY: no initial-constraint or PDE existence proof."];
xx={{x1,x2},{x2,x3}}; hh={{h1,h2},{h2,h3}}; aa={{a1,a2},{a2,-a1}}; zz={z1,z2}; dz={{d11,d12},{d21,d22}}; ep={{0,1},{-1,0}};
ee[m_]:=Sum[ep[[i,j]]m[[i,j]],{i,2},{j,2}];
th=Tr[hh]; tx=Tr[xx]; rr=-kg-(th tx-Tr[hh.xx])/2;
hp=-hh.hh-aa;
xp=dz+Transpose[dz]+2Outer[Times,zz,zz]+rr IdentityMatrix[2]-(hh.xx+xx.hh)/2;
kp=-th kg+ddh-lap;
rp=-kp-(Tr[hp]tx+th Tr[xp])/2+(Tr[hp.xx]+Tr[hh.xp])/2;
divh={dh1,dh2}; dth={dt1,dt2};
divub=ddh-lap-divh.zz-Tr[hh.Transpose[dz]]+dth.zz+th Tr[dz];
zub=zz.divh-zz.dth-zz.hh.zz+th zz.zz;
rhores=FullSimplify[rp+3th rr/2+divub+Tr[xx.aa]/2+zub];
cc=ee[xx.hh]/2; curlz=ee[dz];
cp=ee[xp.hh+xx.hp]/2;
ub={u1,u2}; curlp=-th curlz-curlub-(ep.ub).zz-ee[Outer[Times,zz,hh.zz]]-ee[dz.hh];
sigmares=FullSimplify[curlp+cp+3th(curlz+cc)/2+curlub+Tr[xx.Transpose[ep.aa]]/2+zz.(ep.ub)];
Print["V64 rho residual: ",rhores];Print["V64 sigma residual: ",sigmares];
If[rhores=!=0 || sigmares=!=0,Exit[1]];
