(* 2026-09-07. Exact bounded checks; analytic theorem scope is in the note. *)
ClearAll["Global`*"];
checks = <||>;
put[name_, expr_] := AssociateTo[checks, name -> FullSimplify[expr]];
$Assumptions = 0 < eps < 1 && n > 0 && Element[n, Integers];
cut = Log[eps/r]/Log[1/eps];
put["log-cutoff energy", Integrate[2 Pi r D[cut,r]^2,{r,eps^2,eps},Assumptions->0<eps<1]-2 Pi/Log[1/eps]];
u = Sinh[n Pi (1-x)] Sin[n Pi y]/Sinh[n Pi];
put["harmonic rectangle response", {D[u,{x,2}]+D[u,{y,2}], (u/.x->0)-Sin[n Pi y], (u/.x->1), (u/.y->0), (u/.y->1),(-D[u,x]/.x->0)-n Pi Coth[n Pi]Sin[n Pi y]}];
put["response energy", Integrate[Sin[n Pi y] n Pi Coth[n Pi]Sin[n Pi y],{y,0,1},Assumptions->n>0&&Element[n,Integers]]-n Pi Coth[n Pi]/2];
pauli={{{0,1},{1,0}},{{0,-I},{I,0}},{{1,0},{0,-1}}};
g[t_,v_]:=Cos[t]IdentityMatrix[2]+I Sin[t]Sum[v[[j]]pauli[[j]],{j,3}];
g1=g[alpha,{0,0,1}]; g2=g[beta,{Sin[zeta],0,Cos[zeta]}];
put["SU2 product trace", Tr[g1.g2]/2-(Cos[alpha]Cos[beta]-Sin[alpha]Sin[beta]Cos[zeta])];
g3=g[gamma,{1,0,0}];
put["SU2 transport covariance", Inverse[g3].g1.g3.Inverse[g3].g2.g3-Inverse[g3].g1.g2.g3];
put["same label different outputs", {Tr[g[Pi/3,{0,0,1}].g[Pi/3,{0,0,1}]]/2+1/2,Tr[g[Pi/3,{0,0,1}].g[Pi/3,{0,0,-1}]]/2-1}];
rOne=Array[rr1,{3,3}];rTwo=Array[rr2,{3,3}];aa=Array[a,3];bb=Array[b,3];xx=Array[x,3];
individual=(xx.(aa+rOne.aa)+xx.(Transpose[rTwo].bb+bb))/2;
cross=((Transpose[rOne].xx-xx).bb-aa.(xx-rTwo.xx))/2;
expected=xx.(Transpose[rTwo].(aa+bb)+rOne.(aa+bb))/2;
put["fusion moment-map contraction",individual+cross-expected];
eps3[i_,j_,l_]:=Signature[{i,j,l}];
aa=Table[Array[av[s],{2,2}],{s,3}];
vv=Table[Array[dv[s],{2,2}],{s,3}];
cubic[t_]:=Sum[eps3[i,j,l]Tr[(aa[[i]]+t vv[[i]]).(aa[[j]]+t vv[[j]]).(aa[[l]]+t vv[[l]])],{i,3},{j,3},{l,3}];
put["CS cubic first variation",(D[cubic[t],t]/.t->0)-3 Sum[eps3[i,j,l]Tr[vv[[i]].aa[[j]].aa[[l]]],{i,3},{j,3},{l,3}]];
zeroResidualQ[z_] := And @@ (SameQ[#,0]& /@ Flatten[{z}]);
Print[checks];
passed = And @@ (zeroResidualQ /@ Values[checks]);
Print["ALL PASSED: ", passed, "; groups: ", Length[checks]];
If[!TrueQ[passed],Exit[1]];
