checks = {};
add[name_, res_] := Module[{v=FullSimplify[res]}, AppendTo[checks,{name,AllTrue[Flatten[{v}],TrueQ[#==0]&],v}]];
f1[t_] := a0 + a1 t + a2 t^2 + a3 t^3;
f2[t_] := a0 + b1 t + b2 t^2 + b3 t^3;
f3[t_] := a0 - (a1+b1)t + c2 t^2+c3 t^3;
rem[t_] = Expand[(f3[t]-f1[-t]-f2[-t]+a0)/t^2];
ext[x_,y_] := f1[x]+f2[y]-a0+x y rem[-(x+y)/2];
add["A ray1 extension",ext[r,0]-f1[r]];
add["A ray2 extension",ext[0,r]-f2[r]];
add["A ray3 extension",ext[-r,-r]-f3[r]];
AppendTo[checks,{"A inadmissible slopes 1,0,0",TrueQ[1+0+0!=0],1}];
phu[r_,s_] := r du + ((1-r) au0+r au1) Cos[s]+((1-r) bu0+r bu1) Sin[s];
phw[r_,s_] := r dw + ((1-r) aw0+r aw1) Cos[s]+((1-r) bw0+r bw1) Sin[s];
bulk=Integrate[D[phu[r,s],r](lw+D[phw[r,s],s])-(lu+D[phu[r,s],s])D[phw[r,s],r],{r,0,1},{s,0,2Pi}];
omega=-k bulk/(2Pi);
expected=k(lu dw-lw du)-k/2 (au1 bw1-bu1 aw1-au0 bw0+bu0 aw0);
add["B annulus CPS including harmonic cross term",omega-expected];
add["B canonical zero-mode inverse",{{0,k},{-k,0}}.{{0,-1/k},{1/k,0}}-IdentityMatrix[2]];
add["B clock shift",Exp[I 2Pi (n+1)/k]-Exp[I 2Pi/k]Exp[I 2Pi n/k]];
add["C BCH logarithm through order eight",Normal[Series[-q qq/k Sum[z^j/j,{j,1,8}]-q qq/k Log[1-z],{z,0,8}]]];
add["C triple OPE exponent",q qq+q qqq+qq qqq-((q+qq)qqq+q qq)];
add["C endpoint cancellation exponent",q(-q)/k+q^2/k];
add["C coherent norm generating function",FullSimplify[Sum[Pochhammer[d,j] z^j/Factorial[j],{j,0,Infinity}],Assumptions->0<z<1 && d>0]-(1-z)^(-d)];
aa={a1,a2,a3}; bb={b1,b2,b3}; cc={c1,c2,c3};
add["D invariant pairing sign",aa.Cross[cc,bb]+cc.Cross[aa,bb]];
add["D Lie Jacobi",Expand[Cross[aa,Cross[bb,cc]]+Cross[bb,Cross[cc,aa]]+Cross[cc,Cross[aa,bb]]]];
al[s_] := {Sin[s],Cos[2s],1};
be[s_] := {Cos[s],Sin[2s],Sin[3s]};
ga[s_] := {Sin[2s],1,Cos[3s]};
add["D full circle cocycle Jacobi",Integrate[Cross[al[s],be[s]].D[ga[s],s]+Cross[be[s],ga[s]].D[al[s],s]+Cross[ga[s],al[s]].D[be[s],s],{s,0,2Pi}]];
E1[x_] := e2 hb^2 l1 x^2/2;
E2[x_] := e2 hb^2 l2 x^2/2;
add["E dressed zigzag effective global time",((E1[n+1]-E1[n])t1+(E2[n+1]-E2[n])t2)/hb-e2 hb(l1+l2)(2n+1)/2 ((l1 t1+l2 t2)/(l1+l2))];
add["E arbitrary charge event phase",(E1[n+r]-E1[n])/hb-e2 hb l1(r n+r^2/2)];
add["E diagonal shift preserves moment",(n1+r)-(n2+r)-(n1-n2)];
add["E exponential kernel on diagonal",Exp[I theta (n-n)]-1];
firstResults=checks;
checks={};
add[name_,res_] := Module[{v=FullSimplify[res]},AppendTo[checks,{name,AllTrue[Flatten[{v}],TrueQ[#==0]&],v}]];
sig={{{0,1},{1,0}},{{0,-I},{I,0}},{{1,0},{0,-1}}};
tm=Table[-I sig[[j]]/2,{j,3}];
aa=Table[Sum[ac[i,j]tm[[j]],{j,3}],{i,3}];
bb=Table[Sum[bc[i,j]tm[[j]],{j,3}],{i,3}];
eps[i_,j_,l_]:=Signature[{i,j,l}];
cs3=Sum[eps[i,j,l]Tr[aa[[i]].aa[[j]].aa[[l]]],{i,3},{j,3},{l,3}];
add["D cubic CS canonical decomposition",2cs3/3-2Tr[aa[[1]].(aa[[2]].aa[[3]]-aa[[3]].aa[[2]])]];
var3=Sum[eps[i,j,l]Tr[bb[[i]].aa[[j]].aa[[l]]+aa[[i]].bb[[j]].aa[[l]]+aa[[i]].aa[[j]].bb[[l]]],{i,3},{j,3},{l,3}];
add["D cubic first variation",var3-3Sum[eps[i,j,l]Tr[bb[[i]].aa[[j]].aa[[l]]],{i,3},{j,3},{l,3}]];
add["B physical zero-mode evolution",D[(vp+vm)p^2/(2k),p]-(vp+vm)p/k];
add["C arbitrary oscillator Ward creation",k nn D[Exp[q x z^nn/(k nn)],x]-q z^nn Exp[q x z^nn/(k nn)]];
add["C vertex adjoint zero-mode factor",q (p-q)/k-(q p/k-q^2/k)];
add["E normal-form multiplication restriction",(n1+s)^2 (n2+s) (n1-n2)/. {n1->n,n2->n}];
add["E section respects shift",{(n2+1)-n2-1,(n1+1)-(n2+1)-(n1-n2)}];
add["E compact group zigzag phase",l1 (cs-cr)t1+l2(cs-cr)t2-(l1+l2)(cs-cr)(l1 t1+l2 t2)/(l1+l2)];
allChecks=Join[firstResults,checks];
result=<|"total"->Length[allChecks],"allPassed"->And@@allChecks[[All,2]],"checks"->allChecks|>;
Print[result];
result
