ClearAll["Global`*"];
checks=<||>; put[k_,v_]:=AssociateTo[checks,k->TrueQ[FullSimplify[v]]];
lag=(D[f[t,x,y],t]^2-D[f[t,x,y],x]^2-D[f[t,x,y],y]^2-m^2 f[t,x,y]^2)/2;
dv=D[lag/. f->Function[{tt,xx,yy},f[tt,xx,yy]+eps h[tt,xx,yy]],eps]/.eps->0;
eom=-D[f[t,x,y],{t,2}]+D[f[t,x,y],{x,2}]+D[f[t,x,y],{y,2}]-m^2 f[t,x,y];
div=D[D[f[t,x,y],t] h[t,x,y],t]-D[D[f[t,x,y],x] h[t,x,y],x]-D[D[f[t,x,y],y] h[t,x,y],y];
put["off_shell_first_variation",dv==eom h[t,x,y]+div];
put["energy_divergence",D[(D[f[t,x,y],t]^2+D[f[t,x,y],x]^2+D[f[t,x,y],y]^2+m^2 f[t,x,y]^2)/2,t]-D[D[f[t,x,y],t] D[f[t,x,y],x],x]-D[D[f[t,x,y],t] D[f[t,x,y],y],y]==-D[f[t,x,y],t] eom];
put["release_transposed_flux",pl dq+pr j dq==(pl+j pr) dq];
om={{0,-1},{1,0}}; xh={p,-aa};
put["cps_hamiltonian_sign",xh.om.{u,v}==-(aa u+p v)];
put["reflection_preserves_gradient_energy",({fx,-fy}.{fx,-fy})==fx^2+fy^2];
a[{xx_,yy_}]:={xx+lx,ly-yy}; b[{xx_,yy_}]:={xx,yy+ly};
ainv[{xx_,yy_}]:={xx-lx,ly-yy}; binv[{xx_,yy_}]:={xx,yy-ly};
put["Klein_relation",a[b[ainv[{x,y}]]]==binv[{x,y}]];
put["Klein_double_cover",a[a[{x,y}]]=={x+2lx,y}];
c[{xx_,yy_}]:={lx-xx,yy+ly};
put["double_twist_corner_fixed",a[c[{x,y}]]=={2lx-x,-y}];
put["double_twist_order_two",a[c[a[c[{x,y}]]]]=={x,y}];
modes=Flatten[Table[With[{nn=n,kk=k},Exp[I Pi nn x/lx](Exp[2 Pi I kk y/ly]+(-1)^nn Exp[-2 Pi I kk y/ly])],{n,-3,3},{k,1,3}]];
put["Klein_mode_glide",And@@Table[FullSimplify[(u/.{x->x+lx,y->ly-y})-u,Assumptions->lx>0&&ly>0]==0,{u,modes}]];
put["Klein_mode_normal_match",And@@Table[FullSimplify[(D[u,x]/.x->0)-(D[u,x]/.{x->lx,y->ly-y}),Assumptions->lx>0&&ly>0]==0,{u,modes}]];
put["Klein_mode_y_period",And@@Table[FullSimplify[(u/.y->y+ly)-u,Assumptions->lx>0&&ly>0]==0,{u,modes}]];
put["Klein_eigenvalues",And@@Flatten[Table[With[{u=Exp[I Pi n x/lx](Exp[2 Pi I k y/ly]+(-1)^n Exp[-2 Pi I k y/ly])},FullSimplify[-D[u,{x,2}]-D[u,{y,2}]-((Pi n/lx)^2+(2Pi k/ly)^2)u,Assumptions->lx>0&&ly>0]==0],{n,-3,3},{k,1,3}]]];
put["Klein_zero_y_mode_odd_removed",And@@Table[1+(-1)^n==0,{n,{-3,-1,1,3}}]];
(* Values and first normals match, but third-normal jets fail. *)
bad=x^2(lx-x)^2 y^2(ly-y)^2;
put["low_order_seams_insufficient",And[(bad/.x->0)==(bad/.x->lx),(D[bad,x]/.x->0)==(D[bad,x]/.x->lx),FullSimplify[(D[bad,{x,3}]/.x->0)-(D[bad,{x,3}]/.x->lx)]==-24 lx y^2(ly-y)^2]];
put["corner_trace_jump_divergence",FullSimplify[Integrate[1/(r+s)^2,{r,eps,dd},{s,eps,dd},Assumptions->0<eps<dd]==Log[(dd+eps)^2/(4 dd eps)],Assumptions->0<eps<dd]];
put["point_capacity_cutoff",FullSimplify[Integrate[1/(r Log[1/eps]^2),{r,eps^2,eps},Assumptions->0<eps<1]==1/Log[1/eps],Assumptions->0<eps<1]];
example=Cos[Pi x/lx] Sin[2Pi y/ly];
put["Klein_nonzero_corner_gradient",And[FullSimplify[(example/.{x->x+lx,y->ly-y})-example]==0,FullSimplify[D[example,y]/.{x->0,y->0}]==2Pi/ly,FullSimplify[D[example,y]/.{x->lx,y->0}]==-2Pi/ly]];
rot={{0,1},{-1,0}};
put["sphere_adjacent_collar",And[rot.Transpose[rot]==IdentityMatrix[2],rot.{0,-1}=={-1,0},rot.{0,1}=={1,0},(Transpose[rot].{fx,fy})[[2]]==fx]];
Print[ExportString[<|"checks"->checks,"allPassed"->And@@Values[checks],"count"->Length[checks]|>,"RawJSON"]];
