ClearAll["Global`*"];
checks = {};
add[label_, condition_] := AppendTo[checks, <|"label" -> label, "passed" -> TrueQ[condition]|>];
zero[e_] := And @@ (TrueQ[FullSimplify[# == 0]] & /@ Flatten[{e}]);
uk[x_] := DiagonalMatrix[{1, Exp[-I x]}];
v = {{1, 0}, {0, 0}, {0, 0}, {0, 1}}; p = v.Transpose[v];
h = DiagonalMatrix[{0, 1}]; ho = KroneckerProduct[IdentityMatrix[2], h];
r = {{r00, r01}, {r10, r11}};
a = DiagonalMatrix[{a0, a1}]; ac = DiagonalMatrix[{ac0, ac1}];
seed = Outer[Times, {a0, a1}, {ac0, ac1}];
add["arbitrary product seed produces the claimed energy filter", zero[p.KroneckerProduct[r, seed].p - v.a.r.ac.Transpose[v]]];
add["seed projection norm", zero[Tr[p.KroneckerProduct[r, seed].p] - (a0 ac0 r00 + a1 ac1 r11)]];
phases = DiagonalMatrix[{Exp[I b0], Exp[I b1]}]/Sqrt[2];
phasesC = DiagonalMatrix[{Exp[-I b0], Exp[-I b1]}]/Sqrt[2];
g = {{1, Exp[-I (b0 - b1)]}, {Exp[-I (b1 - b0)], 1}};
add["matching rank-one clock seed cancels all preparation phases", zero[2 (phases.r.phasesC) g - r]];
add["external boundary time shifts the conditional history", zero[uk[x].Transpose[v].MatrixExp[-I ho tau].v - uk[x + tau]]];
add["external stationarity is equivalent to absence of energy coherence", zero[Transpose[v].(ho.v.r.Transpose[v] - v.r.Transpose[v].ho).v - {{0, -r01}, {r10, 0}}]];
o = {{o00, o01}, {o10, o11}}; q = {{q00, q01}, {q10, q11}};
lift[m_, x_] := v.uk[-x].m.uk[x].Transpose[v];
add["full relational operator multiplication", zero[lift[o, x].lift[q, x] - lift[o.q, x]]];
add["two ordered measurements reduce to the usual propagator amplitude", zero[uk[y].Transpose[v].lift[q, y].lift[o, x].v - q.uk[y - x].o.uk[x]]];

c1 = KroneckerProduct[h, IdentityMatrix[2], IdentityMatrix[2]] - KroneckerProduct[IdentityMatrix[2], h, IdentityMatrix[2]];
c2 = KroneckerProduct[IdentityMatrix[2], h, IdentityMatrix[2]] - KroneckerProduct[IdentityMatrix[2], IdentityMatrix[2], h];
p1 = (IdentityMatrix[8] + MatrixExp[-I Pi c1])/2;
p2 = (IdentityMatrix[8] + MatrixExp[-I Pi c2])/2;
v3 = Transpose[{UnitVector[8, 1], UnitVector[8, 8]}];
add["two nested seams have commuting constraints and order-independent projection", zero[c1.c2 - c2.c1] && zero[p1.p2 - p2.p1] && zero[p1.p2 - v3.Transpose[v3]]];
bra[x_] := {1, Exp[-I x]}/Sqrt[2];
doubleReadout = 2 KroneckerProduct[IdentityMatrix[2], {bra[x]}, {bra[y]}].v3;
add["reading both complementary clock factors gives the sum of their readings", zero[doubleReadout - uk[x + y]]];
rr3 = v3.r.Transpose[v3];
oneReadout = KroneckerProduct[IdentityMatrix[2], {bra[x]}, IdentityMatrix[2]];
remainder = 2 oneReadout.rr3.KroneckerProduct[IdentityMatrix[2], Transpose[{bra[-x]}], IdentityMatrix[2]];
reducedA = Table[Sum[remainder[[2 (aa - 1) + k, 2 (bb - 1) + k]], {k, 1, 2}], {aa, 1, 2}, {bb, 1, 2}];
add["discarding the unmeasured complementary energy record removes the relational coherence", zero[reducedA - DiagonalMatrix[{r00, r11}]]];
detuned = DiagonalMatrix[{0, -(1 + delta), 1, -delta}];
add["generic small spectral detuning removes the excited physical state", zero[detuned.v.UnitVector[2, 2] + delta UnitVector[4, 4]] && MatrixRank[detuned /. delta -> 1/100] == 3];
summary = <|"dimensionlessConvention" -> "hbar=1; x=omega t; tau also measured in 1/omega", "checkCount" -> Length[checks], "allPassed" -> And @@ Lookup[checks, "passed"], "checks" -> checks|>;
Print[ExportString[summary, "RawJSON"]];
