ClearAll["Global`*"];
checks={};
check[label_,ex_]:=AppendTo[checks,<|"label"->label,"passed"->TrueQ[FullSimplify[ex,Assumptions->phi>0&&tau<0&&gn>0&&ar>0&&w>0&&Element[{t,s,gc,k},Reals]]]|>];
fLy=-8 lapPhi+rb phi-sig2 phi^-7+(2 tau^2/3)phi^5;
frechet=D[fLy,phi]v-8 lapV;
check["LY_Frechet",frechet==-8 lapV+(rb+7 sig2 phi^-8+(10 tau^2/3)phi^4)v];
lp=(rb phi-sig2 phi^-7+(2 tau^2/3)phi^5)/8;
lhs=-8(phi lapU+u lp+2 gradPU)+(rb+7 sig2 phi^-8+(10 tau^2/3)phi^4)phi u;
rhs=8 phi^5(-phi^-4(lapU+2 gradPU/phi)+(sig2 phi^-12+tau^2/3)u);
check["LY_linearization_equals_CMC_lapse_operator",lhs==rhs];
phi0=Sqrt[-3/tau];
check["hyperbolic_cone_solves_LY",(fLy/.{lapPhi->0,rb->-6,sig2->0,phi->phi0})==0];
check["hyperbolic_linearization_positive_potential",(rb+7 sig2 phi^-8+(10 tau^2/3)phi^4/.{rb->-6,sig2->0,phi->phi0})==24];
check["CMC_norm_K",aa1^2+aa2^2+(-aa1-aa2)^2+tau^2/3==Total[({aa1,aa2,-aa1-aa2}+tau/3)^2]];
check["trace_momentum",Total[(tau-{aa1+tau/3,aa2+tau/3,-aa1-aa2+tau/3}) vol/(16 Pi gn)]==tau vol/(8 Pi gn)];
check["trace_symplectic_potential",2/3 (tau vol/(8 Pi gn))dv/vol==tau dv/(12 Pi gn)];
check["York_endpoint_term",tau dv/(12 Pi gn)-(vol dtau+tau dv)/(12 Pi gn)==-vol dtau/(12 Pi gn)];
pbV[a_,b_]:=D[a,vol]D[b,york]-D[a,york]D[b,vol];
check["York_pair_sign",pbV[york,-vol]==1];
check["LY_time_derivative_source",D[fLy,tau]==4 tau phi^5/3];
check["implicit_volume_time_identity",6(-tau ntau/6)==-tau ntau];
check["cone_lapse",(-tau)phi0^6==D[phi0^6,tau] (tau^2/3)];
beta=ar/(16 Pi gn);
lag=beta (qt^2-qz^2)/2;
check["TT_canonical_momentum",D[lag,qt]==beta qt];
check["TT_wall_response",D[lag,qz]==-beta qz];
hden=pp^2/(2 beta)+beta qz^2/2;
check["TT_Hamiltonian_Legendre",(pp qt-lag/.qt->pp/beta)==hden];
q1=Cos[k(t-z)];q2=Sin[k(t-z)];
check["TT_flux",q1(-beta D[q2,z])-q2(-beta D[q1,z])==beta k];
check["TT_incoming_wave",D[ff[t+z],{t,2}]-D[ff[t+z],{z,2}]==0];
energy=beta(D[ff[t+z],t]^2+D[ff[t+z],z]^2)/2;
check["TT_local_energy_balance",D[energy,t]==D[beta D[ff[t+z],t]D[ff[t+z],z],z]];
bump=Exp[-1/(1-(z-c0)^2/w^2)];
check["compact_bump_nonzero_curvature",(-D[bump,{z,2}]/2/.z->c0)==1/(E w^2)];
jj={{0,1},{-1,0}}; om=ArrayFlatten[{{jj,ConstantArray[0,{2,2}]},{ConstantArray[0,{2,2}],jj}}];
emb={{1,0,0},{0,1,0},{1,0,0},{0,0,1}}; oc=Transpose[emb].om.emb;
check["matching_kernel_example",oc.{0,1,-1}=={0,0,0}&&MatrixRank[oc]==2];
pb[a_,b_]:=Sum[D[a,coords[[i]]]D[b,moms[[i]]]-D[a,moms[[i]]]D[b,coords[[i]]],{i,3}];
coords={t1,t2,q};moms={p1,p2,p}; h1=hh1[t1,t2,q,p];h2=hh2[t1,t2,q,p];
curv=D[h2,t1]-D[h1,t2]-(D[h1,q]D[h2,p]-D[h1,p]D[h2,q]);
check["classical_multitime_curvature_sign",pb[p1+h1,p2+h2]+curv==0];
check["classical_flat_multitime_example",pb[p1+p,p2+q-t1]==0];
sx=PauliMatrix[1];sy=PauliMatrix[2];sz=PauliMatrix[3];id=IdentityMatrix[2];
ha=s sx;hb=t sy; psi={ps1[t,s],ps2[t,s]};
op1[v_]:=-I D[v,t]+ha.v; op2[v_]:=-I D[v,s]+hb.v;
fq=D[hb,t]-D[ha,s]+I(ha.hb-hb.ha);
check["quantum_multitime_curvature_sign",op1[op2[psi]]-op2[op1[psi]]+I fq.psi=={0,0}];
check["quantum_nonflat_example",fq==sy-sx-2 t s sz];
u2=DiagonalMatrix[Exp[-I gc t {1,-1,-1,1}]]; v2=u2.{1,1,1,1}/2;
rho=Outer[Times,v2,Conjugate[v2]];
rhoa=Table[Sum[rho[[2(a-1)+b,2(c-1)+b]],{b,2}],{a,2},{c,2}];
check["interacting_qubits_marginal_purity",Tr[rhoa.rhoa]==(1+Cos[2 gc t]^2)/2];
pa={id,sx,sy,sz}; hgen=Sum[cc[i,j]KroneckerProduct[pa[[i+1]],pa[[j+1]]],{i,0,3},{j,0,3}];
eqs=Flatten[Table[Tr[(hgen.KroneckerProduct[pa[[a+1]],id]-KroneckerProduct[pa[[a+1]],id].hgen).KroneckerProduct[pa[[i+1]],pa[[j+1]]]]==0,{a,1,3},{i,0,3},{j,1,3}]];
ivars=Flatten[Table[cc[i,j],{i,1,3},{j,1,3}]]; sol=Solve[eqs,ivars];
check["two_qubit_full_A_algebra_closure_kills_all_interactions",Length[sol]==1&&And@@Thread[(ivars/.First[sol])==ConstantArray[0,9]]];

ext=Sinh[mm(x+ll)]/Sinh[mm ll];
check["DtN_homogeneous_extension_equation",D[ext,{x,2}]-mm^2 ext==0];
check["DtN_unit_boundary_trace",(ext/.x->-ll)==0&&(ext/.x->0)==1];
check["DtN_outward_response",FullSimplify[(D[ext,x]/.x->0)-mm Coth[mm ll],Assumptions->mm>0&&ll>0]==0];
check["DtN_energy_boundary_identity",D[ext D[ext,x],x]==D[ext,x]^2+mm^2 ext^2];

ExportString[<|"checkCount"->Length[checks],"allPassed"->And@@Lookup[checks,"passed"],"checks"->checks|>,"RawJSON"]
